---

stages:
  - build

.common:
  image: docker
  stage: build
  services:
    - docker:dind
  tags:
    - kubernetes
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://localhost:2375
  script:
    - cd ${BASE:?}
    - export DOCKER_TAG=${PHP_VERSION}
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull --network host --build-arg PHP_VERSION=$PHP_VERSION --tag $CI_REGISTRY_IMAGE:${DOCKER_TAG} --tag $CI_REGISTRY_IMAGE:${DOCKER_TAG}-${CI_COMMIT_SHORT_SHA}  .
    - docker push $CI_REGISTRY_IMAGE:${DOCKER_TAG}
    - docker push $CI_REGISTRY_IMAGE:${DOCKER_TAG}-${CI_COMMIT_SHORT_SHA}
  when: on_success
  only:
    - master

PHP 5.6:
  variables:
    PHP_VERSION: '5.6'
    BASE: 'centos7'
  extends: .common

PHP 7.0:
  variables:
    PHP_VERSION: '7.0'
    BASE: 'centos7'
  extends: .common

PHP 7.1:
  variables:
    PHP_VERSION: '7.1'
    BASE: 'centos7'
  extends: .common

PHP 7.2:
  variables:
    PHP_VERSION: '7.2'
    BASE: 'centos8'
  extends: .common

PHP 7.3:
  variables:
    PHP_VERSION: '7.3'
    BASE: 'centos8'
  extends: .common

PHP 7.4:
  variables:
    PHP_VERSION: '7.4'
    BASE: 'centos8'
  extends: .common

