#!/bin/bash

set -x
IMAGE=$(echo $IMAGE_NAME | sed -E 's/index\.docker\.io\/(.*)\:.*/\1/')
VERSION=$(echo $DOCKER_TAG | sed -E 's/([0-9]).([0-9])/\1\2/g')
docker build --build-arg PHP_VERSION=$VERSION -t $IMAGE:$DOCKER_TAG .
