name: Build Images

on:
  push:
    branches:
      - 'feature/*'

jobs:
  Build_PHP_Ubuntu_Test:
    strategy:
      matrix:
        version: ['7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3']
    environment:
      name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          tags: |
            type=raw,pattern={{version}},value=${{ matrix.version }}-ubuntu
          images: |
            ${{ secrets.IMAGE_NAME }}
            ghcr.io/${{ github.repository }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          push: false
          platforms: linux/amd64,linux/arm64
          build-args: PHP_VERSION=${{ matrix.version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


  Build_PHP_CentOS8_Test:
    strategy:
      matrix:
        version: ['7.2', '7.3', '7.4', '8.0', '8.1']
    environment:
      name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push CentOS based Docker images
        uses: docker/build-push-action@v4
        with:
          push: false
          context: centos8
          platforms: linux/amd64
          build-args: PHP_VERSION=${{ matrix.version }}
          tags: ${{ secrets.IMAGE_NAME }}:${{ matrix.version }}
