name: Build Images

on:
  push:
    branches:
      - 'feature/*'

jobs:
  Build_PHP_Ubuntu_Test:
    strategy:
      matrix:
        version: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1']
    environment:
      name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          push: false
          platforms: linux/amd64,linux/arm64
          build-args: PHP_VERSION=${{ matrix.version }}
          tags: ${{ secrets.IMAGE_NAME }}:${{ matrix.version }}-ubuntu


  Build_PHP_CentOS7_Test:
    strategy:
      matrix:
        version: ['5.6', '7.0', '7.1']
    environment:
      name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push CentOS based Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          push: false
          context: centos7
          platforms: linux/amd64
          build-args: PHP_VERSION=${{ matrix.version }}
          tags: ${{ secrets.IMAGE_NAME }}:${{ matrix.version }}

  Build_PHP_CentOS8_Test:
    strategy:
      matrix:
        version: ['7.2', '7.3', '7.4', '8.0', '8.1']
    environment:
      name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push CentOS based Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          push: false
          context: centos8
          platforms: linux/amd64
          build-args: PHP_VERSION=${{ matrix.version }}
          tags: ${{ secrets.IMAGE_NAME }}:${{ matrix.version }}
